#!/usr/bin/env bash
# This script displays a list of currently running processes.

ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command | head -n 1
ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest | tail -n +2 | sort -nrk1,1
