#!/usr/bin/env bash

# Find the PID of the process
PID=$(pgrep -f "4-to_infinity_and_beyond")

# Check if PID is not empty
if [ -n "$PID" ]; then
    # Terminate the process using SIGTERM
    kill -SIGTERM "$PID"
    echo "Process terminated successfully."
else
    echo "Process not found or already terminated."
fi
