#!/usr/bin/env bash
# This script tells a story based on the content of the file /etc/passwd

while IFS=':' read -r username _ userid groupid _ homedir shell
do
    # Extracting user's full name from the comment field (if available)
    full_name=$(grep -Po "$username:x:\d+:\d+:(.*)::" /etc/passwd | cut -d ':' -f 5)

    # Extracting the user's password (encrypted)
    password=$(grep -Po "$username:x:\d+:\d+:(.*)::" /etc/passwd | cut -d ':' -f 2)

    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $full_name"
done < /etc/passwd
