#!/bin/env bash

# Backup original hosts file
sudo cp /etc/hosts /etc/hosts.backup

# Modify hosts file
sudo sed -i 's/localhost/127.0.0.2/' /etc/hosts
sudo sed -i 's/facebook.com/8.8.8.8/' /etc/hosts

# Check if running on Docker
if grep -q docker /proc/1/cgroup; then
    echo "Running on Docker"
    echo "Remember to revert localhost to 127.0.0.1 if necessary!"
else
    echo "Not running on Docker"
fi

